/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "harmonycloud.cn/multi-cluster-manager/pkg/apis/multicluster/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AggregatedResourceLister helps list AggregatedResources.
// All objects returned here must be treated as read-only.
type AggregatedResourceLister interface {
	// List lists all AggregatedResources in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.AggregatedResource, err error)
	// AggregatedResources returns an object that can list and get AggregatedResources.
	AggregatedResources(namespace string) AggregatedResourceNamespaceLister
	AggregatedResourceListerExpansion
}

// aggregatedResourceLister implements the AggregatedResourceLister interface.
type aggregatedResourceLister struct {
	indexer cache.Indexer
}

// NewAggregatedResourceLister returns a new AggregatedResourceLister.
func NewAggregatedResourceLister(indexer cache.Indexer) AggregatedResourceLister {
	return &aggregatedResourceLister{indexer: indexer}
}

// List lists all AggregatedResources in the indexer.
func (s *aggregatedResourceLister) List(selector labels.Selector) (ret []*v1alpha1.AggregatedResource, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AggregatedResource))
	})
	return ret, err
}

// AggregatedResources returns an object that can list and get AggregatedResources.
func (s *aggregatedResourceLister) AggregatedResources(namespace string) AggregatedResourceNamespaceLister {
	return aggregatedResourceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AggregatedResourceNamespaceLister helps list and get AggregatedResources.
// All objects returned here must be treated as read-only.
type AggregatedResourceNamespaceLister interface {
	// List lists all AggregatedResources in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.AggregatedResource, err error)
	// Get retrieves the AggregatedResource from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.AggregatedResource, error)
	AggregatedResourceNamespaceListerExpansion
}

// aggregatedResourceNamespaceLister implements the AggregatedResourceNamespaceLister
// interface.
type aggregatedResourceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AggregatedResources in the indexer for a given namespace.
func (s aggregatedResourceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.AggregatedResource, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AggregatedResource))
	})
	return ret, err
}

// Get retrieves the AggregatedResource from the indexer for a given namespace and name.
func (s aggregatedResourceNamespaceLister) Get(name string) (*v1alpha1.AggregatedResource, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("aggregatedresource"), name)
	}
	return obj.(*v1alpha1.AggregatedResource), nil
}
