/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// ClusterResourceListerExpansion allows custom methods to be added to
// ClusterResourceLister.
type ClusterResourceListerExpansion interface{}

// ClusterResourceNamespaceListerExpansion allows custom methods to be added to
// ClusterResourceNamespaceLister.
type ClusterResourceNamespaceListerExpansion interface{}

// ClusterSetListerExpansion allows custom methods to be added to
// ClusterSetLister.
type ClusterSetListerExpansion interface{}

// MultiClusterResourceListerExpansion allows custom methods to be added to
// MultiClusterResourceLister.
type MultiClusterResourceListerExpansion interface{}

// MultiClusterResourceNamespaceListerExpansion allows custom methods to be added to
// MultiClusterResourceNamespaceLister.
type MultiClusterResourceNamespaceListerExpansion interface{}

// NamespaceMappingListerExpansion allows custom methods to be added to
// NamespaceMappingLister.
type NamespaceMappingListerExpansion interface{}

// NamespaceMappingNamespaceListerExpansion allows custom methods to be added to
// NamespaceMappingNamespaceLister.
type NamespaceMappingNamespaceListerExpansion interface{}
