/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AggregatedResourceListerExpansion allows custom methods to be added to
// AggregatedResourceLister.
type AggregatedResourceListerExpansion interface{}

// AggregatedResourceNamespaceListerExpansion allows custom methods to be added to
// AggregatedResourceNamespaceLister.
type AggregatedResourceNamespaceListerExpansion interface{}

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// ClusterResourceListerExpansion allows custom methods to be added to
// ClusterResourceLister.
type ClusterResourceListerExpansion interface{}

// ClusterResourceNamespaceListerExpansion allows custom methods to be added to
// ClusterResourceNamespaceLister.
type ClusterResourceNamespaceListerExpansion interface{}

// ClusterSetListerExpansion allows custom methods to be added to
// ClusterSetLister.
type ClusterSetListerExpansion interface{}

// MultiClusterResourceListerExpansion allows custom methods to be added to
// MultiClusterResourceLister.
type MultiClusterResourceListerExpansion interface{}

// MultiClusterResourceNamespaceListerExpansion allows custom methods to be added to
// MultiClusterResourceNamespaceLister.
type MultiClusterResourceNamespaceListerExpansion interface{}

// MultiClusterResourceAggregatePolicyListerExpansion allows custom methods to be added to
// MultiClusterResourceAggregatePolicyLister.
type MultiClusterResourceAggregatePolicyListerExpansion interface{}

// MultiClusterResourceAggregatePolicyNamespaceListerExpansion allows custom methods to be added to
// MultiClusterResourceAggregatePolicyNamespaceLister.
type MultiClusterResourceAggregatePolicyNamespaceListerExpansion interface{}

// MultiClusterResourceAggregateRuleListerExpansion allows custom methods to be added to
// MultiClusterResourceAggregateRuleLister.
type MultiClusterResourceAggregateRuleListerExpansion interface{}

// MultiClusterResourceAggregateRuleNamespaceListerExpansion allows custom methods to be added to
// MultiClusterResourceAggregateRuleNamespaceLister.
type MultiClusterResourceAggregateRuleNamespaceListerExpansion interface{}

// MultiClusterResourceBindingListerExpansion allows custom methods to be added to
// MultiClusterResourceBindingLister.
type MultiClusterResourceBindingListerExpansion interface{}

// MultiClusterResourceBindingNamespaceListerExpansion allows custom methods to be added to
// MultiClusterResourceBindingNamespaceLister.
type MultiClusterResourceBindingNamespaceListerExpansion interface{}

// NamespaceMappingListerExpansion allows custom methods to be added to
// NamespaceMappingLister.
type NamespaceMappingListerExpansion interface{}

// NamespaceMappingNamespaceListerExpansion allows custom methods to be added to
// NamespaceMappingNamespaceLister.
type NamespaceMappingNamespaceListerExpansion interface{}

// ResourceAggregatePolicyListerExpansion allows custom methods to be added to
// ResourceAggregatePolicyLister.
type ResourceAggregatePolicyListerExpansion interface{}

// ResourceAggregatePolicyNamespaceListerExpansion allows custom methods to be added to
// ResourceAggregatePolicyNamespaceLister.
type ResourceAggregatePolicyNamespaceListerExpansion interface{}
