/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "harmonycloud.cn/multi-cluster-manager/pkg/apis/multicluster/v1alpha1"
	scheme "harmonycloud.cn/multi-cluster-manager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AggregatedResourceListsGetter has a method to return a AggregatedResourceListInterface.
// A group's client should implement this interface.
type AggregatedResourceListsGetter interface {
	AggregatedResourceLists(namespace string) AggregatedResourceListInterface
}

// AggregatedResourceListInterface has methods to work with AggregatedResourceList resources.
type AggregatedResourceListInterface interface {
	Create(ctx context.Context, aggregatedResourceList *v1alpha1.AggregatedResourceList, opts v1.CreateOptions) (*v1alpha1.AggregatedResourceList, error)
	Update(ctx context.Context, aggregatedResourceList *v1alpha1.AggregatedResourceList, opts v1.UpdateOptions) (*v1alpha1.AggregatedResourceList, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AggregatedResourceList, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AggregatedResourceListList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AggregatedResourceList, err error)
	AggregatedResourceListExpansion
}

// aggregatedResourceLists implements AggregatedResourceListInterface
type aggregatedResourceLists struct {
	client rest.Interface
	ns     string
}

// newAggregatedResourceLists returns a AggregatedResourceLists
func newAggregatedResourceLists(c *MulticlusterV1alpha1Client, namespace string) *aggregatedResourceLists {
	return &aggregatedResourceLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the aggregatedResourceList, and returns the corresponding aggregatedResourceList object, and an error if there is any.
func (c *aggregatedResourceLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AggregatedResourceList, err error) {
	result = &v1alpha1.AggregatedResourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("aggregatedresourcelists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AggregatedResourceLists that match those selectors.
func (c *aggregatedResourceLists) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AggregatedResourceListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AggregatedResourceListList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("aggregatedresourcelists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aggregatedResourceLists.
func (c *aggregatedResourceLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("aggregatedresourcelists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aggregatedResourceList and creates it.  Returns the server's representation of the aggregatedResourceList, and an error, if there is any.
func (c *aggregatedResourceLists) Create(ctx context.Context, aggregatedResourceList *v1alpha1.AggregatedResourceList, opts v1.CreateOptions) (result *v1alpha1.AggregatedResourceList, err error) {
	result = &v1alpha1.AggregatedResourceList{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("aggregatedresourcelists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aggregatedResourceList).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aggregatedResourceList and updates it. Returns the server's representation of the aggregatedResourceList, and an error, if there is any.
func (c *aggregatedResourceLists) Update(ctx context.Context, aggregatedResourceList *v1alpha1.AggregatedResourceList, opts v1.UpdateOptions) (result *v1alpha1.AggregatedResourceList, err error) {
	result = &v1alpha1.AggregatedResourceList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("aggregatedresourcelists").
		Name(aggregatedResourceList.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aggregatedResourceList).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aggregatedResourceList and deletes it. Returns an error if one occurs.
func (c *aggregatedResourceLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("aggregatedresourcelists").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aggregatedResourceLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("aggregatedresourcelists").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aggregatedResourceList.
func (c *aggregatedResourceLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AggregatedResourceList, err error) {
	result = &v1alpha1.AggregatedResourceList{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("aggregatedresourcelists").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
