/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "harmonycloud.cn/multi-cluster-manager/pkg/apis/multicluster/v1alpha1"
	scheme "harmonycloud.cn/multi-cluster-manager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterResourcesGetter has a method to return a ClusterResourceInterface.
// A group's client should implement this interface.
type ClusterResourcesGetter interface {
	ClusterResources(namespace string) ClusterResourceInterface
}

// ClusterResourceInterface has methods to work with ClusterResource resources.
type ClusterResourceInterface interface {
	Create(ctx context.Context, clusterResource *v1alpha1.ClusterResource, opts v1.CreateOptions) (*v1alpha1.ClusterResource, error)
	Update(ctx context.Context, clusterResource *v1alpha1.ClusterResource, opts v1.UpdateOptions) (*v1alpha1.ClusterResource, error)
	UpdateStatus(ctx context.Context, clusterResource *v1alpha1.ClusterResource, opts v1.UpdateOptions) (*v1alpha1.ClusterResource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterResource, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterResourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterResource, err error)
	ClusterResourceExpansion
}

// clusterResources implements ClusterResourceInterface
type clusterResources struct {
	client rest.Interface
	ns     string
}

// newClusterResources returns a ClusterResources
func newClusterResources(c *MulticlusterV1alpha1Client, namespace string) *clusterResources {
	return &clusterResources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterResource, and returns the corresponding clusterResource object, and an error if there is any.
func (c *clusterResources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterResource, err error) {
	result = &v1alpha1.ClusterResource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterresources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterResources that match those selectors.
func (c *clusterResources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterResourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterResourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterResources.
func (c *clusterResources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterResource and creates it.  Returns the server's representation of the clusterResource, and an error, if there is any.
func (c *clusterResources) Create(ctx context.Context, clusterResource *v1alpha1.ClusterResource, opts v1.CreateOptions) (result *v1alpha1.ClusterResource, err error) {
	result = &v1alpha1.ClusterResource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterResource).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterResource and updates it. Returns the server's representation of the clusterResource, and an error, if there is any.
func (c *clusterResources) Update(ctx context.Context, clusterResource *v1alpha1.ClusterResource, opts v1.UpdateOptions) (result *v1alpha1.ClusterResource, err error) {
	result = &v1alpha1.ClusterResource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterresources").
		Name(clusterResource.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterResource).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterResources) UpdateStatus(ctx context.Context, clusterResource *v1alpha1.ClusterResource, opts v1.UpdateOptions) (result *v1alpha1.ClusterResource, err error) {
	result = &v1alpha1.ClusterResource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterresources").
		Name(clusterResource.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterResource).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterResource and deletes it. Returns an error if one occurs.
func (c *clusterResources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterresources").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterResources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterresources").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterResource.
func (c *clusterResources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterResource, err error) {
	result = &v1alpha1.ClusterResource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterresources").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
