/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "harmonycloud.cn/multi-cluster-manager/pkg/apis/multicluster/v1alpha1"
	scheme "harmonycloud.cn/multi-cluster-manager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MultiClusterResourceAggregateRulesGetter has a method to return a MultiClusterResourceAggregateRuleInterface.
// A group's client should implement this interface.
type MultiClusterResourceAggregateRulesGetter interface {
	MultiClusterResourceAggregateRules(namespace string) MultiClusterResourceAggregateRuleInterface
}

// MultiClusterResourceAggregateRuleInterface has methods to work with MultiClusterResourceAggregateRule resources.
type MultiClusterResourceAggregateRuleInterface interface {
	Create(ctx context.Context, multiClusterResourceAggregateRule *v1alpha1.MultiClusterResourceAggregateRule, opts v1.CreateOptions) (*v1alpha1.MultiClusterResourceAggregateRule, error)
	Update(ctx context.Context, multiClusterResourceAggregateRule *v1alpha1.MultiClusterResourceAggregateRule, opts v1.UpdateOptions) (*v1alpha1.MultiClusterResourceAggregateRule, error)
	UpdateStatus(ctx context.Context, multiClusterResourceAggregateRule *v1alpha1.MultiClusterResourceAggregateRule, opts v1.UpdateOptions) (*v1alpha1.MultiClusterResourceAggregateRule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MultiClusterResourceAggregateRule, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MultiClusterResourceAggregateRuleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiClusterResourceAggregateRule, err error)
	MultiClusterResourceAggregateRuleExpansion
}

// multiClusterResourceAggregateRules implements MultiClusterResourceAggregateRuleInterface
type multiClusterResourceAggregateRules struct {
	client rest.Interface
	ns     string
}

// newMultiClusterResourceAggregateRules returns a MultiClusterResourceAggregateRules
func newMultiClusterResourceAggregateRules(c *MulticlusterV1alpha1Client, namespace string) *multiClusterResourceAggregateRules {
	return &multiClusterResourceAggregateRules{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the multiClusterResourceAggregateRule, and returns the corresponding multiClusterResourceAggregateRule object, and an error if there is any.
func (c *multiClusterResourceAggregateRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MultiClusterResourceAggregateRule, err error) {
	result = &v1alpha1.MultiClusterResourceAggregateRule{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregaterules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MultiClusterResourceAggregateRules that match those selectors.
func (c *multiClusterResourceAggregateRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MultiClusterResourceAggregateRuleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MultiClusterResourceAggregateRuleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregaterules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested multiClusterResourceAggregateRules.
func (c *multiClusterResourceAggregateRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregaterules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a multiClusterResourceAggregateRule and creates it.  Returns the server's representation of the multiClusterResourceAggregateRule, and an error, if there is any.
func (c *multiClusterResourceAggregateRules) Create(ctx context.Context, multiClusterResourceAggregateRule *v1alpha1.MultiClusterResourceAggregateRule, opts v1.CreateOptions) (result *v1alpha1.MultiClusterResourceAggregateRule, err error) {
	result = &v1alpha1.MultiClusterResourceAggregateRule{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregaterules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterResourceAggregateRule).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a multiClusterResourceAggregateRule and updates it. Returns the server's representation of the multiClusterResourceAggregateRule, and an error, if there is any.
func (c *multiClusterResourceAggregateRules) Update(ctx context.Context, multiClusterResourceAggregateRule *v1alpha1.MultiClusterResourceAggregateRule, opts v1.UpdateOptions) (result *v1alpha1.MultiClusterResourceAggregateRule, err error) {
	result = &v1alpha1.MultiClusterResourceAggregateRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregaterules").
		Name(multiClusterResourceAggregateRule.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterResourceAggregateRule).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *multiClusterResourceAggregateRules) UpdateStatus(ctx context.Context, multiClusterResourceAggregateRule *v1alpha1.MultiClusterResourceAggregateRule, opts v1.UpdateOptions) (result *v1alpha1.MultiClusterResourceAggregateRule, err error) {
	result = &v1alpha1.MultiClusterResourceAggregateRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregaterules").
		Name(multiClusterResourceAggregateRule.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterResourceAggregateRule).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the multiClusterResourceAggregateRule and deletes it. Returns an error if one occurs.
func (c *multiClusterResourceAggregateRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregaterules").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *multiClusterResourceAggregateRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregaterules").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched multiClusterResourceAggregateRule.
func (c *multiClusterResourceAggregateRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiClusterResourceAggregateRule, err error) {
	result = &v1alpha1.MultiClusterResourceAggregateRule{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("multiclusterresourceaggregaterules").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
