/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "harmonycloud.cn/multi-cluster-manager/pkg/apis/multicluster/v1alpha1"
	scheme "harmonycloud.cn/multi-cluster-manager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MultiClusterResourceBindingsGetter has a method to return a MultiClusterResourceBindingInterface.
// A group's client should implement this interface.
type MultiClusterResourceBindingsGetter interface {
	MultiClusterResourceBindings(namespace string) MultiClusterResourceBindingInterface
}

// MultiClusterResourceBindingInterface has methods to work with MultiClusterResourceBinding resources.
type MultiClusterResourceBindingInterface interface {
	Create(ctx context.Context, multiClusterResourceBinding *v1alpha1.MultiClusterResourceBinding, opts v1.CreateOptions) (*v1alpha1.MultiClusterResourceBinding, error)
	Update(ctx context.Context, multiClusterResourceBinding *v1alpha1.MultiClusterResourceBinding, opts v1.UpdateOptions) (*v1alpha1.MultiClusterResourceBinding, error)
	UpdateStatus(ctx context.Context, multiClusterResourceBinding *v1alpha1.MultiClusterResourceBinding, opts v1.UpdateOptions) (*v1alpha1.MultiClusterResourceBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MultiClusterResourceBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MultiClusterResourceBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiClusterResourceBinding, err error)
	MultiClusterResourceBindingExpansion
}

// multiClusterResourceBindings implements MultiClusterResourceBindingInterface
type multiClusterResourceBindings struct {
	client rest.Interface
	ns     string
}

// newMultiClusterResourceBindings returns a MultiClusterResourceBindings
func newMultiClusterResourceBindings(c *MulticlusterV1alpha1Client, namespace string) *multiClusterResourceBindings {
	return &multiClusterResourceBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the multiClusterResourceBinding, and returns the corresponding multiClusterResourceBinding object, and an error if there is any.
func (c *multiClusterResourceBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MultiClusterResourceBinding, err error) {
	result = &v1alpha1.MultiClusterResourceBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterresourcebindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MultiClusterResourceBindings that match those selectors.
func (c *multiClusterResourceBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MultiClusterResourceBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MultiClusterResourceBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterresourcebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested multiClusterResourceBindings.
func (c *multiClusterResourceBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterresourcebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a multiClusterResourceBinding and creates it.  Returns the server's representation of the multiClusterResourceBinding, and an error, if there is any.
func (c *multiClusterResourceBindings) Create(ctx context.Context, multiClusterResourceBinding *v1alpha1.MultiClusterResourceBinding, opts v1.CreateOptions) (result *v1alpha1.MultiClusterResourceBinding, err error) {
	result = &v1alpha1.MultiClusterResourceBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("multiclusterresourcebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterResourceBinding).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a multiClusterResourceBinding and updates it. Returns the server's representation of the multiClusterResourceBinding, and an error, if there is any.
func (c *multiClusterResourceBindings) Update(ctx context.Context, multiClusterResourceBinding *v1alpha1.MultiClusterResourceBinding, opts v1.UpdateOptions) (result *v1alpha1.MultiClusterResourceBinding, err error) {
	result = &v1alpha1.MultiClusterResourceBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("multiclusterresourcebindings").
		Name(multiClusterResourceBinding.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterResourceBinding).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *multiClusterResourceBindings) UpdateStatus(ctx context.Context, multiClusterResourceBinding *v1alpha1.MultiClusterResourceBinding, opts v1.UpdateOptions) (result *v1alpha1.MultiClusterResourceBinding, err error) {
	result = &v1alpha1.MultiClusterResourceBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("multiclusterresourcebindings").
		Name(multiClusterResourceBinding.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterResourceBinding).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the multiClusterResourceBinding and deletes it. Returns an error if one occurs.
func (c *multiClusterResourceBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiclusterresourcebindings").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *multiClusterResourceBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiclusterresourcebindings").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched multiClusterResourceBinding.
func (c *multiClusterResourceBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiClusterResourceBinding, err error) {
	result = &v1alpha1.MultiClusterResourceBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("multiclusterresourcebindings").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
