/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "harmonycloud.cn/multi-cluster-manager/pkg/apis/multicluster/v1alpha1"
	scheme "harmonycloud.cn/multi-cluster-manager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MultiClusterResourceAggregatePoliciesGetter has a method to return a MultiClusterResourceAggregatePolicyInterface.
// A group's client should implement this interface.
type MultiClusterResourceAggregatePoliciesGetter interface {
	MultiClusterResourceAggregatePolicies(namespace string) MultiClusterResourceAggregatePolicyInterface
}

// MultiClusterResourceAggregatePolicyInterface has methods to work with MultiClusterResourceAggregatePolicy resources.
type MultiClusterResourceAggregatePolicyInterface interface {
	Create(ctx context.Context, multiClusterResourceAggregatePolicy *v1alpha1.MultiClusterResourceAggregatePolicy, opts v1.CreateOptions) (*v1alpha1.MultiClusterResourceAggregatePolicy, error)
	Update(ctx context.Context, multiClusterResourceAggregatePolicy *v1alpha1.MultiClusterResourceAggregatePolicy, opts v1.UpdateOptions) (*v1alpha1.MultiClusterResourceAggregatePolicy, error)
	UpdateStatus(ctx context.Context, multiClusterResourceAggregatePolicy *v1alpha1.MultiClusterResourceAggregatePolicy, opts v1.UpdateOptions) (*v1alpha1.MultiClusterResourceAggregatePolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MultiClusterResourceAggregatePolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MultiClusterResourceAggregatePolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiClusterResourceAggregatePolicy, err error)
	MultiClusterResourceAggregatePolicyExpansion
}

// multiClusterResourceAggregatePolicies implements MultiClusterResourceAggregatePolicyInterface
type multiClusterResourceAggregatePolicies struct {
	client rest.Interface
	ns     string
}

// newMultiClusterResourceAggregatePolicies returns a MultiClusterResourceAggregatePolicies
func newMultiClusterResourceAggregatePolicies(c *MulticlusterV1alpha1Client, namespace string) *multiClusterResourceAggregatePolicies {
	return &multiClusterResourceAggregatePolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the multiClusterResourceAggregatePolicy, and returns the corresponding multiClusterResourceAggregatePolicy object, and an error if there is any.
func (c *multiClusterResourceAggregatePolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MultiClusterResourceAggregatePolicy, err error) {
	result = &v1alpha1.MultiClusterResourceAggregatePolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregatepolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MultiClusterResourceAggregatePolicies that match those selectors.
func (c *multiClusterResourceAggregatePolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MultiClusterResourceAggregatePolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MultiClusterResourceAggregatePolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregatepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested multiClusterResourceAggregatePolicies.
func (c *multiClusterResourceAggregatePolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregatepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a multiClusterResourceAggregatePolicy and creates it.  Returns the server's representation of the multiClusterResourceAggregatePolicy, and an error, if there is any.
func (c *multiClusterResourceAggregatePolicies) Create(ctx context.Context, multiClusterResourceAggregatePolicy *v1alpha1.MultiClusterResourceAggregatePolicy, opts v1.CreateOptions) (result *v1alpha1.MultiClusterResourceAggregatePolicy, err error) {
	result = &v1alpha1.MultiClusterResourceAggregatePolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregatepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterResourceAggregatePolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a multiClusterResourceAggregatePolicy and updates it. Returns the server's representation of the multiClusterResourceAggregatePolicy, and an error, if there is any.
func (c *multiClusterResourceAggregatePolicies) Update(ctx context.Context, multiClusterResourceAggregatePolicy *v1alpha1.MultiClusterResourceAggregatePolicy, opts v1.UpdateOptions) (result *v1alpha1.MultiClusterResourceAggregatePolicy, err error) {
	result = &v1alpha1.MultiClusterResourceAggregatePolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregatepolicies").
		Name(multiClusterResourceAggregatePolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterResourceAggregatePolicy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *multiClusterResourceAggregatePolicies) UpdateStatus(ctx context.Context, multiClusterResourceAggregatePolicy *v1alpha1.MultiClusterResourceAggregatePolicy, opts v1.UpdateOptions) (result *v1alpha1.MultiClusterResourceAggregatePolicy, err error) {
	result = &v1alpha1.MultiClusterResourceAggregatePolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregatepolicies").
		Name(multiClusterResourceAggregatePolicy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterResourceAggregatePolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the multiClusterResourceAggregatePolicy and deletes it. Returns an error if one occurs.
func (c *multiClusterResourceAggregatePolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregatepolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *multiClusterResourceAggregatePolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiclusterresourceaggregatepolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched multiClusterResourceAggregatePolicy.
func (c *multiClusterResourceAggregatePolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiClusterResourceAggregatePolicy, err error) {
	result = &v1alpha1.MultiClusterResourceAggregatePolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("multiclusterresourceaggregatepolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
