/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "harmonycloud.cn/multi-cluster-manager/pkg/apis/multicluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterResources implements ClusterResourceInterface
type FakeClusterResources struct {
	Fake *FakeMulticlusterV1alpha1
	ns   string
}

var clusterresourcesResource = schema.GroupVersionResource{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Resource: "clusterresources"}

var clusterresourcesKind = schema.GroupVersionKind{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Kind: "ClusterResource"}

// Get takes name of the clusterResource, and returns the corresponding clusterResource object, and an error if there is any.
func (c *FakeClusterResources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterresourcesResource, c.ns, name), &v1alpha1.ClusterResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterResource), err
}

// List takes label and field selectors, and returns the list of ClusterResources that match those selectors.
func (c *FakeClusterResources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterresourcesResource, clusterresourcesKind, c.ns, opts), &v1alpha1.ClusterResourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterResourceList{ListMeta: obj.(*v1alpha1.ClusterResourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterResourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterResources.
func (c *FakeClusterResources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterresourcesResource, c.ns, opts))

}

// Create takes the representation of a clusterResource and creates it.  Returns the server's representation of the clusterResource, and an error, if there is any.
func (c *FakeClusterResources) Create(ctx context.Context, clusterResource *v1alpha1.ClusterResource, opts v1.CreateOptions) (result *v1alpha1.ClusterResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterresourcesResource, c.ns, clusterResource), &v1alpha1.ClusterResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterResource), err
}

// Update takes the representation of a clusterResource and updates it. Returns the server's representation of the clusterResource, and an error, if there is any.
func (c *FakeClusterResources) Update(ctx context.Context, clusterResource *v1alpha1.ClusterResource, opts v1.UpdateOptions) (result *v1alpha1.ClusterResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterresourcesResource, c.ns, clusterResource), &v1alpha1.ClusterResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterResource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterResources) UpdateStatus(ctx context.Context, clusterResource *v1alpha1.ClusterResource, opts v1.UpdateOptions) (*v1alpha1.ClusterResource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clusterresourcesResource, "status", c.ns, clusterResource), &v1alpha1.ClusterResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterResource), err
}

// Delete takes name of the clusterResource and deletes it. Returns an error if one occurs.
func (c *FakeClusterResources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clusterresourcesResource, c.ns, name), &v1alpha1.ClusterResource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterResources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusterresourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterResourceList{})
	return err
}

// Patch applies the patch and returns the patched clusterResource.
func (c *FakeClusterResources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterresourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterResource), err
}
