/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "harmonycloud.cn/multi-cluster-manager/pkg/apis/multicluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeResourceAggregatePolicyLists implements ResourceAggregatePolicyListInterface
type FakeResourceAggregatePolicyLists struct {
	Fake *FakeMulticlusterV1alpha1
	ns   string
}

var resourceaggregatepolicylistsResource = schema.GroupVersionResource{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Resource: "resourceaggregatepolicylists"}

var resourceaggregatepolicylistsKind = schema.GroupVersionKind{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Kind: "ResourceAggregatePolicyList"}

// Get takes name of the resourceAggregatePolicyList, and returns the corresponding resourceAggregatePolicyList object, and an error if there is any.
func (c *FakeResourceAggregatePolicyLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ResourceAggregatePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(resourceaggregatepolicylistsResource, c.ns, name), &v1alpha1.ResourceAggregatePolicyList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceAggregatePolicyList), err
}

// List takes label and field selectors, and returns the list of ResourceAggregatePolicyLists that match those selectors.
func (c *FakeResourceAggregatePolicyLists) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ResourceAggregatePolicyListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(resourceaggregatepolicylistsResource, resourceaggregatepolicylistsKind, c.ns, opts), &v1alpha1.ResourceAggregatePolicyListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceAggregatePolicyListList), err
}

// Watch returns a watch.Interface that watches the requested resourceAggregatePolicyLists.
func (c *FakeResourceAggregatePolicyLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(resourceaggregatepolicylistsResource, c.ns, opts))

}

// Create takes the representation of a resourceAggregatePolicyList and creates it.  Returns the server's representation of the resourceAggregatePolicyList, and an error, if there is any.
func (c *FakeResourceAggregatePolicyLists) Create(ctx context.Context, resourceAggregatePolicyList *v1alpha1.ResourceAggregatePolicyList, opts v1.CreateOptions) (result *v1alpha1.ResourceAggregatePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(resourceaggregatepolicylistsResource, c.ns, resourceAggregatePolicyList), &v1alpha1.ResourceAggregatePolicyList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceAggregatePolicyList), err
}

// Update takes the representation of a resourceAggregatePolicyList and updates it. Returns the server's representation of the resourceAggregatePolicyList, and an error, if there is any.
func (c *FakeResourceAggregatePolicyLists) Update(ctx context.Context, resourceAggregatePolicyList *v1alpha1.ResourceAggregatePolicyList, opts v1.UpdateOptions) (result *v1alpha1.ResourceAggregatePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(resourceaggregatepolicylistsResource, c.ns, resourceAggregatePolicyList), &v1alpha1.ResourceAggregatePolicyList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceAggregatePolicyList), err
}

// Delete takes name of the resourceAggregatePolicyList and deletes it. Returns an error if one occurs.
func (c *FakeResourceAggregatePolicyLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(resourceaggregatepolicylistsResource, c.ns, name), &v1alpha1.ResourceAggregatePolicyList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeResourceAggregatePolicyLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(resourceaggregatepolicylistsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ResourceAggregatePolicyListList{})
	return err
}

// Patch applies the patch and returns the patched resourceAggregatePolicyList.
func (c *FakeResourceAggregatePolicyLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ResourceAggregatePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resourceaggregatepolicylistsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ResourceAggregatePolicyList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceAggregatePolicyList), err
}
