/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "harmonycloud.cn/multi-cluster-manager/pkg/apis/multicluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMultiClusterResourceAggregateRuleLists implements MultiClusterResourceAggregateRuleListInterface
type FakeMultiClusterResourceAggregateRuleLists struct {
	Fake *FakeMulticlusterV1alpha1
	ns   string
}

var multiclusterresourceaggregaterulelistsResource = schema.GroupVersionResource{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Resource: "multiclusterresourceaggregaterulelists"}

var multiclusterresourceaggregaterulelistsKind = schema.GroupVersionKind{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Kind: "MultiClusterResourceAggregateRuleList"}

// Get takes name of the multiClusterResourceAggregateRuleList, and returns the corresponding multiClusterResourceAggregateRuleList object, and an error if there is any.
func (c *FakeMultiClusterResourceAggregateRuleLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MultiClusterResourceAggregateRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(multiclusterresourceaggregaterulelistsResource, c.ns, name), &v1alpha1.MultiClusterResourceAggregateRuleList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregateRuleList), err
}

// List takes label and field selectors, and returns the list of MultiClusterResourceAggregateRuleLists that match those selectors.
func (c *FakeMultiClusterResourceAggregateRuleLists) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MultiClusterResourceAggregateRuleListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(multiclusterresourceaggregaterulelistsResource, multiclusterresourceaggregaterulelistsKind, c.ns, opts), &v1alpha1.MultiClusterResourceAggregateRuleListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregateRuleListList), err
}

// Watch returns a watch.Interface that watches the requested multiClusterResourceAggregateRuleLists.
func (c *FakeMultiClusterResourceAggregateRuleLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(multiclusterresourceaggregaterulelistsResource, c.ns, opts))

}

// Create takes the representation of a multiClusterResourceAggregateRuleList and creates it.  Returns the server's representation of the multiClusterResourceAggregateRuleList, and an error, if there is any.
func (c *FakeMultiClusterResourceAggregateRuleLists) Create(ctx context.Context, multiClusterResourceAggregateRuleList *v1alpha1.MultiClusterResourceAggregateRuleList, opts v1.CreateOptions) (result *v1alpha1.MultiClusterResourceAggregateRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(multiclusterresourceaggregaterulelistsResource, c.ns, multiClusterResourceAggregateRuleList), &v1alpha1.MultiClusterResourceAggregateRuleList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregateRuleList), err
}

// Update takes the representation of a multiClusterResourceAggregateRuleList and updates it. Returns the server's representation of the multiClusterResourceAggregateRuleList, and an error, if there is any.
func (c *FakeMultiClusterResourceAggregateRuleLists) Update(ctx context.Context, multiClusterResourceAggregateRuleList *v1alpha1.MultiClusterResourceAggregateRuleList, opts v1.UpdateOptions) (result *v1alpha1.MultiClusterResourceAggregateRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(multiclusterresourceaggregaterulelistsResource, c.ns, multiClusterResourceAggregateRuleList), &v1alpha1.MultiClusterResourceAggregateRuleList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregateRuleList), err
}

// Delete takes name of the multiClusterResourceAggregateRuleList and deletes it. Returns an error if one occurs.
func (c *FakeMultiClusterResourceAggregateRuleLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(multiclusterresourceaggregaterulelistsResource, c.ns, name), &v1alpha1.MultiClusterResourceAggregateRuleList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMultiClusterResourceAggregateRuleLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(multiclusterresourceaggregaterulelistsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MultiClusterResourceAggregateRuleListList{})
	return err
}

// Patch applies the patch and returns the patched multiClusterResourceAggregateRuleList.
func (c *FakeMultiClusterResourceAggregateRuleLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiClusterResourceAggregateRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(multiclusterresourceaggregaterulelistsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MultiClusterResourceAggregateRuleList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregateRuleList), err
}
