/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "harmonycloud.cn/multi-cluster-manager/pkg/apis/multicluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMultiClusterResourceAggregateRules implements MultiClusterResourceAggregateRuleInterface
type FakeMultiClusterResourceAggregateRules struct {
	Fake *FakeMulticlusterV1alpha1
	ns   string
}

var multiclusterresourceaggregaterulesResource = schema.GroupVersionResource{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Resource: "multiclusterresourceaggregaterules"}

var multiclusterresourceaggregaterulesKind = schema.GroupVersionKind{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Kind: "MultiClusterResourceAggregateRule"}

// Get takes name of the multiClusterResourceAggregateRule, and returns the corresponding multiClusterResourceAggregateRule object, and an error if there is any.
func (c *FakeMultiClusterResourceAggregateRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MultiClusterResourceAggregateRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(multiclusterresourceaggregaterulesResource, c.ns, name), &v1alpha1.MultiClusterResourceAggregateRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregateRule), err
}

// List takes label and field selectors, and returns the list of MultiClusterResourceAggregateRules that match those selectors.
func (c *FakeMultiClusterResourceAggregateRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MultiClusterResourceAggregateRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(multiclusterresourceaggregaterulesResource, multiclusterresourceaggregaterulesKind, c.ns, opts), &v1alpha1.MultiClusterResourceAggregateRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MultiClusterResourceAggregateRuleList{ListMeta: obj.(*v1alpha1.MultiClusterResourceAggregateRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.MultiClusterResourceAggregateRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested multiClusterResourceAggregateRules.
func (c *FakeMultiClusterResourceAggregateRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(multiclusterresourceaggregaterulesResource, c.ns, opts))

}

// Create takes the representation of a multiClusterResourceAggregateRule and creates it.  Returns the server's representation of the multiClusterResourceAggregateRule, and an error, if there is any.
func (c *FakeMultiClusterResourceAggregateRules) Create(ctx context.Context, multiClusterResourceAggregateRule *v1alpha1.MultiClusterResourceAggregateRule, opts v1.CreateOptions) (result *v1alpha1.MultiClusterResourceAggregateRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(multiclusterresourceaggregaterulesResource, c.ns, multiClusterResourceAggregateRule), &v1alpha1.MultiClusterResourceAggregateRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregateRule), err
}

// Update takes the representation of a multiClusterResourceAggregateRule and updates it. Returns the server's representation of the multiClusterResourceAggregateRule, and an error, if there is any.
func (c *FakeMultiClusterResourceAggregateRules) Update(ctx context.Context, multiClusterResourceAggregateRule *v1alpha1.MultiClusterResourceAggregateRule, opts v1.UpdateOptions) (result *v1alpha1.MultiClusterResourceAggregateRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(multiclusterresourceaggregaterulesResource, c.ns, multiClusterResourceAggregateRule), &v1alpha1.MultiClusterResourceAggregateRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregateRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMultiClusterResourceAggregateRules) UpdateStatus(ctx context.Context, multiClusterResourceAggregateRule *v1alpha1.MultiClusterResourceAggregateRule, opts v1.UpdateOptions) (*v1alpha1.MultiClusterResourceAggregateRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(multiclusterresourceaggregaterulesResource, "status", c.ns, multiClusterResourceAggregateRule), &v1alpha1.MultiClusterResourceAggregateRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregateRule), err
}

// Delete takes name of the multiClusterResourceAggregateRule and deletes it. Returns an error if one occurs.
func (c *FakeMultiClusterResourceAggregateRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(multiclusterresourceaggregaterulesResource, c.ns, name), &v1alpha1.MultiClusterResourceAggregateRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMultiClusterResourceAggregateRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(multiclusterresourceaggregaterulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MultiClusterResourceAggregateRuleList{})
	return err
}

// Patch applies the patch and returns the patched multiClusterResourceAggregateRule.
func (c *FakeMultiClusterResourceAggregateRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiClusterResourceAggregateRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(multiclusterresourceaggregaterulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.MultiClusterResourceAggregateRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregateRule), err
}
