/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "harmonycloud.cn/multi-cluster-manager/pkg/apis/multicluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMultiClusterResourceAggregatePolicyLists implements MultiClusterResourceAggregatePolicyListInterface
type FakeMultiClusterResourceAggregatePolicyLists struct {
	Fake *FakeMulticlusterV1alpha1
	ns   string
}

var multiclusterresourceaggregatepolicylistsResource = schema.GroupVersionResource{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Resource: "multiclusterresourceaggregatepolicylists"}

var multiclusterresourceaggregatepolicylistsKind = schema.GroupVersionKind{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Kind: "MultiClusterResourceAggregatePolicyList"}

// Get takes name of the multiClusterResourceAggregatePolicyList, and returns the corresponding multiClusterResourceAggregatePolicyList object, and an error if there is any.
func (c *FakeMultiClusterResourceAggregatePolicyLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MultiClusterResourceAggregatePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(multiclusterresourceaggregatepolicylistsResource, c.ns, name), &v1alpha1.MultiClusterResourceAggregatePolicyList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregatePolicyList), err
}

// List takes label and field selectors, and returns the list of MultiClusterResourceAggregatePolicyLists that match those selectors.
func (c *FakeMultiClusterResourceAggregatePolicyLists) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MultiClusterResourceAggregatePolicyListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(multiclusterresourceaggregatepolicylistsResource, multiclusterresourceaggregatepolicylistsKind, c.ns, opts), &v1alpha1.MultiClusterResourceAggregatePolicyListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregatePolicyListList), err
}

// Watch returns a watch.Interface that watches the requested multiClusterResourceAggregatePolicyLists.
func (c *FakeMultiClusterResourceAggregatePolicyLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(multiclusterresourceaggregatepolicylistsResource, c.ns, opts))

}

// Create takes the representation of a multiClusterResourceAggregatePolicyList and creates it.  Returns the server's representation of the multiClusterResourceAggregatePolicyList, and an error, if there is any.
func (c *FakeMultiClusterResourceAggregatePolicyLists) Create(ctx context.Context, multiClusterResourceAggregatePolicyList *v1alpha1.MultiClusterResourceAggregatePolicyList, opts v1.CreateOptions) (result *v1alpha1.MultiClusterResourceAggregatePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(multiclusterresourceaggregatepolicylistsResource, c.ns, multiClusterResourceAggregatePolicyList), &v1alpha1.MultiClusterResourceAggregatePolicyList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregatePolicyList), err
}

// Update takes the representation of a multiClusterResourceAggregatePolicyList and updates it. Returns the server's representation of the multiClusterResourceAggregatePolicyList, and an error, if there is any.
func (c *FakeMultiClusterResourceAggregatePolicyLists) Update(ctx context.Context, multiClusterResourceAggregatePolicyList *v1alpha1.MultiClusterResourceAggregatePolicyList, opts v1.UpdateOptions) (result *v1alpha1.MultiClusterResourceAggregatePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(multiclusterresourceaggregatepolicylistsResource, c.ns, multiClusterResourceAggregatePolicyList), &v1alpha1.MultiClusterResourceAggregatePolicyList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregatePolicyList), err
}

// Delete takes name of the multiClusterResourceAggregatePolicyList and deletes it. Returns an error if one occurs.
func (c *FakeMultiClusterResourceAggregatePolicyLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(multiclusterresourceaggregatepolicylistsResource, c.ns, name), &v1alpha1.MultiClusterResourceAggregatePolicyList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMultiClusterResourceAggregatePolicyLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(multiclusterresourceaggregatepolicylistsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MultiClusterResourceAggregatePolicyListList{})
	return err
}

// Patch applies the patch and returns the patched multiClusterResourceAggregatePolicyList.
func (c *FakeMultiClusterResourceAggregatePolicyLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiClusterResourceAggregatePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(multiclusterresourceaggregatepolicylistsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MultiClusterResourceAggregatePolicyList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceAggregatePolicyList), err
}
