/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "harmonycloud.cn/multi-cluster-manager/pkg/apis/multicluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAggregatedResourceLists implements AggregatedResourceListInterface
type FakeAggregatedResourceLists struct {
	Fake *FakeMulticlusterV1alpha1
	ns   string
}

var aggregatedresourcelistsResource = schema.GroupVersionResource{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Resource: "aggregatedresourcelists"}

var aggregatedresourcelistsKind = schema.GroupVersionKind{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Kind: "AggregatedResourceList"}

// Get takes name of the aggregatedResourceList, and returns the corresponding aggregatedResourceList object, and an error if there is any.
func (c *FakeAggregatedResourceLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AggregatedResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(aggregatedresourcelistsResource, c.ns, name), &v1alpha1.AggregatedResourceList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AggregatedResourceList), err
}

// List takes label and field selectors, and returns the list of AggregatedResourceLists that match those selectors.
func (c *FakeAggregatedResourceLists) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AggregatedResourceListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(aggregatedresourcelistsResource, aggregatedresourcelistsKind, c.ns, opts), &v1alpha1.AggregatedResourceListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AggregatedResourceListList), err
}

// Watch returns a watch.Interface that watches the requested aggregatedResourceLists.
func (c *FakeAggregatedResourceLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(aggregatedresourcelistsResource, c.ns, opts))

}

// Create takes the representation of a aggregatedResourceList and creates it.  Returns the server's representation of the aggregatedResourceList, and an error, if there is any.
func (c *FakeAggregatedResourceLists) Create(ctx context.Context, aggregatedResourceList *v1alpha1.AggregatedResourceList, opts v1.CreateOptions) (result *v1alpha1.AggregatedResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(aggregatedresourcelistsResource, c.ns, aggregatedResourceList), &v1alpha1.AggregatedResourceList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AggregatedResourceList), err
}

// Update takes the representation of a aggregatedResourceList and updates it. Returns the server's representation of the aggregatedResourceList, and an error, if there is any.
func (c *FakeAggregatedResourceLists) Update(ctx context.Context, aggregatedResourceList *v1alpha1.AggregatedResourceList, opts v1.UpdateOptions) (result *v1alpha1.AggregatedResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(aggregatedresourcelistsResource, c.ns, aggregatedResourceList), &v1alpha1.AggregatedResourceList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AggregatedResourceList), err
}

// Delete takes name of the aggregatedResourceList and deletes it. Returns an error if one occurs.
func (c *FakeAggregatedResourceLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(aggregatedresourcelistsResource, c.ns, name), &v1alpha1.AggregatedResourceList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAggregatedResourceLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(aggregatedresourcelistsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AggregatedResourceListList{})
	return err
}

// Patch applies the patch and returns the patched aggregatedResourceList.
func (c *FakeAggregatedResourceLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AggregatedResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(aggregatedresourcelistsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AggregatedResourceList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AggregatedResourceList), err
}
